routes/web.php
<?php


Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::resource('gov/admin', 'AdminController');

Route::get('', 'ArticleController@index')->name('news.index');

//Route::get('news', 'ArticleController@index')->name('news.index');
Route::get('news/{slug}', 'ArticleController@show')->name('news.show');
Route::get('/search', 'ArticleController@search')->name('news.search');
Route::get('/tag/{slug}', 'ArticleController@search')->name('news.tag');


Route::get('tag/{slug}', 'ArticleController@tag')->name('news.tag');
Route::post('mail/', 'MailController@send')->name('mail.send');

resources/views/admin/create.blade.php
@extends('layouts.app')
@section('content')
    @include('errors')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="container">
        <h3>Create post</h3>

        <div class="row">
            <br class="col-md-12 ">
                {!! Form::open(['route'=>['admin.store'],  'method'=>"post",'enctype'=>"multipart/form-data",]) !!}
                <br class="form-group">
                    <label for="party-time">Заголовок</label>
                   <input type="text" class="form-control" name="title" value="{{old('title')}}">
                <br> <input type="file" name="preview"></br>
                    <br>
                    <label for="party-time">Описание</label>
                    <textarea name="description" id="" cols="10" class="form-control"> {{old('description')}}</textarea>
                </br>
                    <label for="party-time">Теги</label>
                    <textarea name="hashtag" id="" cols="10" class="form-control"> {{old('description')}}</textarea>
                    </br>
                    <input name="names[]" type="file" multiple >
            <br>  <button class="btn btn-success"> Submit</button></br>
                </div>
                {!! Form::close() !!}
                </div>
            </div>
        </div>


@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')
@section('content')
    @include('errors')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="container">
        <h3>Edit article # - {{$article->id}}</h3>

        <div class="row">
            <div class="col-md-12 ">
                {!! Form::open(['method'=>'put', 'route'=>['admin.update', $article->id]] ) !!}
                <div class="form-group">
                    <label for="party-time">Заголовок</label>
                    <input type="text" class="form-control" name="title" value="{{$article->title}}">
                      <input type="file" name="preview">   <br>
                    <label for="party-time">Описание</label>
                    <textarea name="description" id="" cols="10" class="form-control"> {{$article->description}}</textarea>
                    </br>
                    <label for="party-time">Теги</label>
                    <textarea name="hashtag" id="" cols="10" class="form-control"> </textarea>
                    </br>
                    <input name="names[]" type="file" multiple >
                    <button class="btn btn-warning"> Submit</button>
                </div>



                {!! Form::close() !!}
            </div>
        </div>
    </div>


@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
   <div class="container">

           <h3>More.celebrities</h3>
           <a href="admin/create" class="btn btn-success">Create</a>
          <div class="row">
           <div class="col-md-10 col=md-offset-1">
               <table class="table">
                   <thead>
                   <tr>
                       <td>ID</td>
                       <td>Title</td>
                        <td>Preview</td>
                        <td>Date</td>
                   </tr>
                   </thead>
                   <tbody>
                   @foreach($articles as $article)
                   <tr>
                       <td>{{$article->id}}</td>
                       <td>{{$article->title}}</td>
                       <td><img src="/uploads/{{$article->preview}}.jpg"
                                width="150" height="130" ></td>
                       <td>{{$article->created_at}}</td>
                       <td>
                           <a href="{{route('admin.show', $article->id)}}">
                               <i class="glyphicon glyphicon-eye-open"></i>
                           </a>
                           <a href="{{route('admin.edit', $article->id)}}">
                               <i class="glyphicon glyphicon-edit"></i>
                           </a>
                           {!! Form::open(['method'=>'DELETE',
                           'route' => ['admin.destroy', $article->id]])!!}
                           <button onclick='return confirm("Are you sure?")'>
                               <i class="glyphicon glyphicon-remove"></i></button>
                           {!! Form::close() !!}

                       </td>
                   </tr>
                   @endforeach
                   </tbody>
               </table>
           </div>
   </div>
   </div>

@endsection

resources/views/admin/show.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="container">

        <h3>More Celebrities/id={{$article->id}}</h3>

        <div class="row">
            <div class="col-md-10 col=md-offset-1">
                <table class="table">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Title</td>
                        <td>Description</td>
                        <td>Preview</td>
                        <td>Hashtag</td>
                        <td>Date</td>
                        <td>Photos</td>

                    </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>{{$article->id}}</td>
                            <td>{{$article->title}}</td>
                            <td>{{$article->description}}</td>
                            <td><img src="/uploads/{{$article->preview}}.jpg"
                                     width="150" height="130" ></td>
                            <td>
                                @foreach($tags as $tag)
                                {{$tag->name}}
                                @endforeach
                            </td>
                            <td>{{$article->created_at}}</td>
                            <td>
                                @foreach($images as $image)
                                    <img src="/uploads/{{$image->names}}.jpg"
                                         width="150" height="130" >
                                   @endforeach
                            </td>

                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
@endsection